version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports: 
      - '5432:5432'
  video-service:
    build:
      context: ./video-service
    environment:
      APP_PORT: 8080
      PG_DATABASE: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USERNAME: postgres
      PG_PASSWORD: 1234
      START_TIMEOUT: 15000
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - '8080:8080'
volumes:
  db-data:
    external: true